### ISSUE TITLE
Delta hardfork tracking

### ISSUE THREAD

**Issue by zhouop0** [optimism-java/hildr#68]
- [x] [span_batch_tx](https://github.com/optimism-java/hildr/issues/83)
- [x] [span_batch_txs](https://github.com/optimism-java/hildr/issues/85)
- [x] [span_batch_recoverV](https://github.com/optimism-java/hildr/issues/87)
- [x] [span_batch_fulltx](https://github.com/optimism-java/hildr/issues/89)
- [x] [raw_span_batch](https://github.com/optimism-java/hildr/issues/91)
- [x] [raw_span_batch_to_span_batch](https://github.com/optimism-java/hildr/issues/93)

**Comment by GrapeBaBa** [comment]
https://op-tip.notion.site/Delta-Node-Upgrade-Guide-c4627f9dc02e4ed884d2420e8a9f8777
